name: Build and Push Docker Image with Docker

on: workflow_dispatch
  

env:
  DOCKER_REGISTRY: akashkam


jobs:
  build:
    runs-on: self-hosted

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Login to Docker registry by Podman
      run: |
        sudo docker login  -u "${{ secrets.DOCKER_USERNAME }}" -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Voting Application Build Image Using Podman
      run: |
        cd vote/
        sudo docker build -t ${{ env.DOCKER_REGISTRY }}/vote .
        sudo docker push ${{ env.DOCKER_REGISTRY }}/vote
        
    - name: Result Application Build Image Using Podman
      run: |
        cd result/
        sudo docker build -t ${{ env.DOCKER_REGISTRY }}/result .
        sudo docker push ${{ env.DOCKER_REGISTRY }}/result 
  

    - name: Worker Application Build Image Using Podman
      run: |
        cd worker/
        sudo docker build -t ${{ env.DOCKER_REGISTRY }}/worker .
        sudo docker push ${{ env.DOCKER_REGISTRY }}/worker
        
    - name: Setup kubectl and plugins
      uses: marcofranssen/setup-kubectl@v0.3.0
      with:
        kubectlVersion: latest


    - uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}
        context: akscluster-002
   
    - name: Test connection to AKS cluster
      run: |
        ls
        cd k8s-specifications-docker/
        kubectl create ns docker
        kubectl apply -f . -n docker
